# Generated by Django 4.2.4 on 2023-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='blue', max_length=128),
            preserve_default=False,
        ),
    ]
